### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Meatballs1** [kevthehermit/SpearPhisher#1]
Would be good to list packages at start such as 
`apt-get install apache2 mysql-server php5 postfix`

Some of the optional PIP install things dont seem available, wrong name, no name

Apache setup missing `a2enmod wsgi`

Database name is incorrect in mysql config. `spearphsiher`

AllowedHosts setting should be `['*']` not `[*]`

**Comment by Meatballs1** [comment]
n.b. a2ensite needs to be above the apache restart to stop it failing :)

**Comment by kevthehermit** [comment]
Thanks making changes now :)

**Comment by Meatballs1** [comment]
I think INSTALLED APPS should be `django_admin_bootstrapped`

**Comment by kevthehermit** [comment]
Made the changes thanks
